---

- name: create the grub configuration
  template:
    src: etc/default/grub.j2
    dest: '{{ grub_cfg }}'
    owner: root
    group: root
    mode: 0644
    seuser: system_u
    serole: object_r
    setype: bootloader_etc_t
    selevel: s0
  notify:
    - 'grub update config'
